### ISSUE TITLE
DSR_FSRMFileScreenTemplateAction.psm1: report type always return false with multiple reports

### ISSUE THREAD

**Issue by BWille1** [dsccommunity/FSRMDsc#8]
There seems to be a bug in the check for report types.  On line 680, the comparison ...($action.ReportTypes -ne $ReportTypes) ... won't work as ReportTypes is defined as an array, which will always return false.

An alternate solution might be to use the "Compare-Object" Cmdlet for this:
"-and (-not (Compare-Object -ReferenceObject $action.ReportTypes -DifferenceObject $ReportTypes)))"

**Comment by PlagueHO** [comment]
Thanks for submitting this @BWille1. I have completed the changes as well as some other minor fixes related to this. I'll release this new version now.

**Comment by PlagueHO** [comment]
@BWille1 - I've released this new version to the PS Gallery:
https://www.powershellgallery.com/packages/FSRMDsc/2.4.0.169
